[package]
name = "platformer"
version = "0.1.0"
authors = ["Shamyl Zakariya <shamyl@gmail.com>"]
edition = "2018"

[features]
default = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.40"
bytemuck = { version = "1.5.1", features = ["derive"] }
futures = "0.3.14"
image = "0.23.14"
imgui = "0.7.0"
imgui-wgpu = "0.14.0"
imgui-winit-support = "0.7.0"
rand = "0.8.3"
raw-window-handle = "0.3.3"
structopt = "0.3.21"
wgpu = "0.7.1"
wgpu-subscriber = "0.1.0"
winit = "0.24.0"
xml-rs = "0.8.3"
gilrs = "0.8.1"
rodio = "0.13.1"

[dependencies.cgmath]
version = "0.18.0"
features = ["swizzle"]

[build-dependencies]
anyhow = "1.0.40"
fs_extra = "1.2.0"
glob = "0.3.0"
rayon = "1.5.0"
shaderc = "0.7.2"

