[package]
name = "platformer"
version = "0.1.0"
authors = ["Shamyl Zakariya <shamyl@gmail.com>"]
edition = "2018"

[features]
default = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
bytemuck = { version = "1.4", features = ["derive"] }
image = "0.23"
winit = "0.22"
cgmath = "0.17"
env_logger = "0.7"
log = "0.4"
rayon = "1.4"
tobj = "2.0"
wgpu = "0.6"
futures = "0.3"
imgui = "0.5"
imgui-wgpu = "0.11.0"
wgpu-subscriber = "0.1"
raw-window-handle = "0.3"


[dependencies.imgui-winit-support]
version = "0.5"
default-features = false
features = ["winit-22"]

[build-dependencies]
anyhow = "1.0"
fs_extra = "1.1"
glob = "0.3"
rayon = "1.4"
shaderc = "0.6"

